Update coverity-analysis.yml

diff --git a/.github/workflows/coverity-analysis.yml b/.github/workflows/coverity-analysis.yml
--- a/.github/workflows/coverity-analysis.yml
+++ b/.github/workflows/coverity-analysis.yml
@@ -40,7 +40,7 @@ jobs:
           echo "Coverity Tool installed successfully"
       - name: Build with Coverity
         run: |
-          coverity_tool/bin/cov-build --dir cov-int sudo ./BuildLinux.sh -u || true
+          coverity_tool/bin/cov-build --dir cov-int ./BuildLinux.sh -ds || echo 'Failed to build using Coverity'
       - name: Compress with bzip2
         run: |
           tar cjvf myproject.tar.bz2 cov-int
